Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
  
# Master Node
  config.vm.define "master" do |master|
    master.vm.network "forwarded_port", guest: 8080, host: 8080
    master.vm.box = "ubuntu/xenial64"
    master.vm.provision "shell", path: "provision_master.sh"
  end

  # Slave Node 1
  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/xenial64"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.1.20"
    node1.vm.provision "shell", path: "provision_slave.sh"
  end
  # Slave Node 2
  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/xenial64"
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.1.30"
    node2.vm.provision "shell", path: "provision_slave.sh"
  end

  
  
  
end